# Álgebra linear básica (dot, transpose, inv)

**Explicação teórica simples

NumPy também é usado para operações de álgebra linear, essenciais em ciência de dados, machine learning e engenharia.
As principais funções são:

* `np.dot(a, b)` → produto escalar ou multiplicação matricial.
* `np.transpose(a)` → transposição de uma matriz (linhas ↔ colunas).
* `np.linalg.inv(a)` → matriz inversa (usada em sistemas lineares).
* `np.linalg.det(a)` → determinante.

🧠 Em resumo:

*Matrizes são como tabelas de números — e o NumPy permite manipulá-las como objetos matemáticos de verdade.*

In [2]:
import numpy as np

# Criando matrizes
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Multiplicação matricial
print("Produto matricial (A · B):\n", np.dot(A, B))

# Transposição
print("Transposta de A:\n", np.transpose(A))

# Determinante e inversa
print("Determinante de A:", np.linalg.det(A))
print("Inversa de A:\n", np.linalg.inv(A))

Produto matricial (A · B):
 [[19 22]
 [43 50]]
Transposta de A:
 [[1 3]
 [2 4]]
Determinante de A: -2.0000000000000004
Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


Exemplo do mundo real

Em modelos de regressão linear, a equação normal envolve a operação:

`β = (XᵀX)⁻¹Xᵀy`

Você pode resolvê-la com NumPy facilmente:

In [3]:
X = np.array([[1, 1], [1, 2], [1, 3]])  # variável independente (ex: tempo)
y = np.array([2, 3, 4])                 # variável dependente (ex: vendas)

beta = np.linalg.inv(X.T @ X) @ X.T @ y
print("Coeficientes da regressão:", beta)

Coeficientes da regressão: [1. 1.]


# Exercícios

**Fácil**

Crie uma matriz `[[2, 4], [6, 8]]` e:

* Mostre sua transposta.

* Calcule seu determinante com `np.linalg.det()`.


In [ ]:
a = np.array([[2,4], [6, 8]])
print("A transposta de (a) é:\n", np.transpose(a))
print("A determinante de (a) é:", np.linalg.det(a))

A transposta de (a) é:
 [[2 6]
 [4 8]]
A determinante de (a) é: -8


**Intermediário**

Crie duas matrizes:

`A = np.array([[1, 2], [3, 4]])`

`B = np.array([[2, 0], [1, 3]])`

Calcule o produto matricial A · B.

In [8]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

print(A @ B)

[[ 4  6]
 [10 12]]


**Desafio**

Crie uma matriz:

`M = np.array([[4, 7], [2, 6]])`

1. Mostre o determinante e a inversa.

2. Verifique se a multiplicação de M pela sua inversa resulta na matriz identidade (np.eye(2)).



In [ ]:
M = np.array([[4, 7], [2, 6]])

inversa = np.linalg.inv(M)
print("Determinante:", round(np.linalg.det(M)))
print("Inversa:\n", inversa)

print(np.allclose(inversa @ M, np.eye(2))) #np.eye(2) matriz identidade 2x2 [[1, 0], [0, 1]]



Determinante: 10
Inversa:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
True
