# Tipos de dados e operações matemáticas vetorizadas

Tipos de dados e operações matemáticas vetorizadas
Explicação teórica simples

No NumPy, cada array possui um tipo de dado (dtype), que define que tipo de valores ele guarda:

* `int` → números inteiros

* `float` → números com casas decimais

* `bool` → valores True/False

* `complex` → números complexos

Além disso, NumPy permite operações matemáticas vetorizadas, ou seja, operações que se aplicam a todos os elementos do array de uma só vez, sem precisar de loops.

Exemplo rápido: se você tem temperaturas em Celsius e quer converter para Fahrenheit, você pode aplicar a fórmula a todo array diretamente.

**Demonstração prática**

In [3]:
import numpy as np

#Array de inteiros
arr_int = np.array([1, 2, 3], dtype=int)
print(arr_int.dtype)

#Array de floats
arr_float = np.array([1, 2, 3], dtype=float)
print(arr_float.dtype)

#Operações vetorizadas
temperaturas_c = np.array([22, 23, 21, 20])
temperaturas_f = temperaturas_c * 9/5 + 32 #conversão para Fahrenheit
print(temperaturas_f)

# perações entre arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # Saída: [5 7 9]
print(a * b)  # Saída: [ 4 10 18]

int64
float64
[71.6 73.4 69.8 68. ]
[5 7 9]
[ 4 10 18]


***Exercícios***

**Fácil**: Crie um array com valores [1, 3, 5] e transforme em float.


In [6]:
arr_float = np.array([1, 3, 5], dtype=float)
print(arr_float.dtype)

float64


**Intermediário**: Um array com alturas em metros [1.70, 1.82, 1.65]. Converta para centímetros usando operação vetorizada.

In [7]:
alturas_m = np.array([1.70, 1.82, 1.65])

alturas_cm = alturas_m * 100
print(alturas_cm)

[170. 182. 165.]


**Desafio**: Dois arrays representam vendas de dois produtos em 7 dias. Calcule o total vendido por dia e depois o total geral de vendas, usando apenas operações vetorizadas.

In [ ]:
vendas_1= np.random.randint(1, 100, 7) #1 é o minímo e 100 é o máximo
vendas_2= np.random.randint(1, 100, 7)

total = vendas_1 + vendas_2
print("Vendas do Produto 1:", vendas_1)
print("Vendas do Produto 2:", vendas_2)
print("\n--- Estatisticas---")
print("Total vendido por dia:", total)
print("Total geral de vendas:", np.sum(total))

Vendas do Produto 1: [35 29 67 24 69 65 40]
Vendas do Produto 2: [89 46 53 65 17  8 32]

--- Estatisticas---
Total vendido por dia: [124  75 120  89  86  73  72]
Total geral de vendas: 639
