# Introdução ao NumPy e criação de arrays
Explicação teórica simples

O NumPy é a biblioteca central para análise numérica em Python. Seu principal objeto é o ndarray, que é um array multidimensional eficiente. Ele permite:

* Armazenar dados numéricos em grandes volumes.

* Fazer operações matemáticas de forma rápida.

* Substituir loops do Python por operações vetorizadas.

Existem formas comuns de criar arrays:

* array: converte listas ou tuplas em arrays.

* arange: gera sequências de números com passo definido.

* linspace: gera sequências de números igualmente espaçados entre dois valores.

In [1]:
import numpy as np

#Criando um array a partir de uma lista
arr1 = np.array([10, 20, 30])
print(arr1)

#Criando um array usando arange (0 a 9)
arr2 = np.arange(10)
print(arr2)

#Criando um array com linspace (5 valores entre 0 e 1)
arr3 = np.linspace(0, 1, 5)
print(arr3)



[10 20 30]
[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


**Explicação linha a linha:**

1. `np.array([10,20,30])` → cria um array a partir de uma lista Python.
2. `np.arange(10)` → cria um array de 0 até 9.
3. `np.linspace(0,1,5)` → cria 5 números igualmente espaçados de 0 a 1.

***Exercícios***

Fácil: Crie um array de números de 10 a 50, de 5 em 5.

In [3]:
arr1 = np.arange(10, 55, 5) #Inicio, fim, passo
print(arr1)

[10 15 20 25 30 35 40 45 50]


Intermediário: Crie 10 valores de um sensor de temperatura igualmente espaçados entre 20 e 30°C usando `linspace.`

In [ ]:
arr2 = np.linspace(20, 30, 10)
print(arr2)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


Desafio: Crie um array de 30 dias e simule a temperatura diária com valores aleatórios entre 18 e 28°C usando arange e operações NumPy.

In [ ]:
dias = np.arange(1, 31)

temperaturas = np.random.randint(18, 29, 30)

print("Dias", dias)
print("Temperaturas", temperaturas)
print("\n--- Estatisticas ---")
print(f"Temperatura média: {np.mean(temperaturas):.1f}°c") #mean(temperaturas) → calcula a média
print(f"Temperatura máxima: {np.max(temperaturas)}°c")
print(f"Temperatura mínima: {np.min(temperaturas)}°c")
print(f"Dias com temperatura > 25°c: {np.sum(temperaturas > 25)}") #sum(temperaturas) conta quantos dias tiveram temperatura acima de 25°C

Dias [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
Temperaturas [27 18 26 19 22 19 24 18 24 24 25 24 27 21 26 23 26 21 24 27 24 18 20 25
 26 24 20 19 28 20]

--- Estatisticas ---
Temperatura média: 23.0°c
Temperatura máxima: 28°c
Temperatura mínima: 18°c
Dias com temperatura > 25°c: 8
