# Indexação, fatiamento e filtragem
**Explicação teórica simples**

No NumPy, você pode acessar partes específicas de um array (ou subconjuntos de dados) sem precisar copiar todo o conteúdo.
Isso é feito com três técnicas principais:

1. **Indexação** → pegar um elemento pelo seu índice.

2. **Fatiamento (slicing)** → pegar uma sequência de elementos.

3. **Filtragem (boolean indexing)** → selecionar elementos com base em uma condição lógica.

Essas operações são essenciais para preparar e limpar dados antes da análise.

In [3]:
import numpy as np

#Criando um array simples
arr = np.array([10, 20, 30, 40, 50])

#Indexação
print(arr[0])
print(arr[-1])

#Fatiamento
print(arr[1:4]) #Do índice 1 ao 3
print(arr[:3]) # Três primeiros
print(arr[::2]) #Pulando de 2 em 2

#Filtragem (condições)
filtro = arr > 25
print(filtro)
print(arr[filtro])

10
50
[20 30 40]
[10 20 30]
[10 30 50]
[False False  True  True  True]
[30 40 50]


# Exercícios

**Fácil**

Crie um array de `[10, 20, 30, 40, 50]` e:

* Mostre o segundo e o último elemento.
* Mostre os três primeiros números usando fatiamento.

In [5]:
arr = np.array([10, 20, 30, 40, 50])
print(f"Primeiro elemento: {arr[0]}, último elemento: {arr[-1]}")
print("Os 3 primeiros números são:", arr[:3])

Primeiro elemento: 10, último elemento: 50
Os 3 primeiros números são: [10 20 30]


**Intermediário**

Crie um array com as idades `[15, 22, 18, 30, 45, 12, 25]`.
Mostre apenas as idades maiores ou iguais a 18 (maiores de idade).

In [ ]:
idades = np.array([15, 22, 18, 30, 45, 12, 25])
filtro_idades = idades >= 18
print(idades[filtro_idades])

[22 18 30 45 25]


**Desafio**

Você tem as notas de uma turma:

`notas = np.array([6.5, 8.2, 9.0, 5.4, 7.8, 4.9, 8.7])`

1. Mostre as notas acima de 7.0.
2. Depois, substitua as notas abaixo de 6.0 por 6.0 (usando indexação e atribuição).
3. Mostre o array atualizado.

In [ ]:
notas = np.array([6.5, 8.2, 9.0, 5.4, 7.8, 4.9, 8.7])

notas_acima_7 = notas > 7.0
print(f"Notas acima de 7.0: {notas[notas_acima_7]}")

notas[notas < 6.0] = 6.0
print("Notas atualizadas:", notas)

Notas acima de 7.0: [8.2 9.  7.8 8.7]
Notas atualizadas: [6.5 8.2 9.  6.  7.8 6.  8.7]
