# Teste Prático Final – NumPy

Responda com código Python (sem comentários explicativos) para cada questão.

**1️⃣ Criação e operações**

Crie um array de 12 números inteiros de 10 a 120 (de 10 em 10).
Mostre apenas os números maiores que 60 e calcule sua média.

In [32]:
import numpy as np

arr = np.arange(10, 121, 10)
filtro_maior_60 = arr > 60
arr_filtrado = arr[filtro_maior_60]
print(arr)
print("Números maiores que 60:", arr_filtrado)
print("Media dos números maiores que 60:", np.mean(arr_filtrado))
print("Media geral:", np.mean(arr))


[ 10  20  30  40  50  60  70  80  90 100 110 120]
Números maiores que 60: [ 70  80  90 100 110 120]
Media dos números maiores que 60: 95.0
Media geral: 65.0


**2️⃣ Estatísticas**

Crie um array com 8 valores representando o faturamento semanal de uma loja:
`[1200, 1340, 1500, 1700, 1650, 1800, 1900, 2100]`

Calcule:

* média, mediana e desvio padrão;

* e mostre quais semanas tiveram faturamento acima da média.

In [ ]:
faturamento = np.array([1200, 1340, 1500, 1700, 1650, 1800, 1900, 2100])

media = np.mean(faturamento)
mediana = np.median(faturamento)
desvio_padrao = np.std(faturamento)
filtro_acima_media = faturamento > media
indice_acima_media = np.where(faturamento > media)[0] + 1

print("Faturamento da semanal:", faturamento)
print("Média", media)
print("Mediana", mediana)
print("Desvio Padrão:", round(desvio_padrao, 2))
print("As semanas acima da média foram: ", indice_acima_media)


Faturamento da semanal: [1200 1340 1500 1700 1650 1800 1900 2100]
Média 1648.75
Mediana 1675.0
Desvio Padrão: 276.38
As semanas acima da média foram:  [4 5 6 7 8]


**3️⃣ Álgebra Linear**

Crie as matrizes:

`A = np.array([[2, 1], [7, 3]])`

`B = np.array([[4, 2], [5, 6]])`

Calcule:

* o produto matricial `A · B`;

* o determinante de `A`;

* e a inversa de `A`.

In [49]:
a = np.array([[2, 1], [7, 3]])
b = np.array([[4, 2], [5, 6]])

print("A * B =\n", a @ b)
print("\nDeterminante de A:",np.linalg.det(a))
print("\nInversa de A:\n",np.linalg.inv(a))

A * B =
 [[13 10]
 [43 32]]

Determinante de A: -1.0000000000000002

Inversa de A:
 [[-3.  1.]
 [ 7. -2.]]


**4️⃣ Simulação**

Simule 20 dias de preços de uma ação, começando em R$50.
Use variações diárias com média de 0.001 e desvio padrão de 0.02.
Mostre:

* o preço final,

* o dia mais alto e o mais baixo,

* e o retorno total em porcentagem.

In [164]:
desvio, media = 0.02, 0.001
varicao = np.random.randn(20) * desvio + media
acao = 50 * np.cumprod(1 + varicao)
valor_max = np.argmax(acao) + 1
valor_min = np.argmin(acao) + 1
retorno = (acao[-1] / acao[0] -1) * 100

print("Valores diarios:\n", np.round(acao, 2))
print("\nPreço final: R$", round(acao[-1], 2))
print(f"Dia do valor mais alto : {valor_max}\nDia do valor mais baixo: {valor_min}")
print(f"Retorno total: {retorno:.2f}%")

Valores diarios:
 [50.46 50.89 51.84 52.23 52.22 51.08 50.6  51.05 51.94 51.78 52.04 51.28
 51.63 51.87 50.98 50.64 51.09 52.41 53.09 53.92]

Preço final: R$ 53.92
Dia do valor mais alto : 20
Dia do valor mais baixo: 1
Retorno total: 6.85%


**5️⃣ Desafio Analítico**

Usando apenas NumPy, gere 1000 valores simulando alturas humanas com média 170 cm e desvio padrão 10.
Mostre:

* média e desvio padrão obtidos,

* quantas pessoas têm mais de 185 cm,

* e o percentual que isso representa.

In [ ]:
desvio, media = 10, 170
alturas = np.random.randn(1000) * desvio + media
media_altura = round(np.mean(alturas), 2)
quantidade_maior_185 = np.sum(alturas > 185)
porcentagem_185 = (quantidade_maior_185 * 100) / alturas.size

print("Média de altura:", media_altura)
print(f"Tem {quantidade_maior_185} pessoas maior que 185cm. Que corresponde a {porcentagem_185:.2f}%")


Média de altura: 170.96
Tem 74 pessoas maior que 185cm. Que corresponde a 7.40%
